### ISSUE TITLE
Remove particles.js landing page

### ISSUE THREAD

**Issue by willtheorangeguy** [willtheorangeguy/willtheorangeguy.github.io#37]
Remove the landing page, but find a way to incorperate it somewhere else.

**Comment by JASKIRAT11011** [comment]
@willtheorangeguy plzz assign me the following issue

**Comment by willtheorangeguy** [comment]
Done!

**Comment by JASKIRAT11011** [comment]
i have forked your repo and clone it on my VS, what exactly needs to be done?

**Comment by JASKIRAT11011** [comment]
@willtheorangeguy i have made a PR of deleting particle.js , can you please confirm

**Comment by JASKIRAT11011** [comment]
@willtheorangeguy can u please merge it and close the issue or assign me hacktober fest or hacktober fest accepted tag so i can be double sure if contribution is valid

**Comment by willtheorangeguy** [comment]
I merged the pull request, and I will now close the issue as well. I have also added the hacktoberfest tag to the PR.

**Comment by JASKIRAT11011** [comment]
thank you man
